title: null
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5773362
  brandStrength: 0.7964554
  rhythmicContrast: 0.5204082
  brandColors:
    - '#0D0C04'
    - '#495543'
    - '#657F66'
    - '#A3C7AA'
  lightness: 0.5332975
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-70164307-1
  facebook: null
name: Lony Meyer
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.06928033
layout_spectrum: 0.49519
