name: Lony Meyer Photography
favicon: null
layout_spectrum: 0.50168
typography_spectrum: 0.1361702
title: 'Art & Photography'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70164307-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.3659574
  saturation: 0.606383
  rhythmicContrast: 0.6659575
purpose: []
