layout_spectrum: 0.7507806047451415
typography_spectrum: 0.47953313303733297
color:
  saturation: 0.8593311682472577
  brandStrength: 0.23191026688138447
  lightness: 0.5838959833811784
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  rhythmicContrast: 0.5325672050409647
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-70164307-1
  facebook: null
author:
  name: ©Copyright 2016
  email: lony@lonymeyer.com
  url: lonymeyer.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/73da66f3-68cf-45b2-9961-b24e223ffb9b.png
name: Lony Meyer Photography
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Norway
    id: 6ef0d8d6-b65c-44d9-966d-1e70050eadea
    type: content
  - name: My Bio
    id: b7389f8e-5b1b-4015-b072-cfd39223b0b0
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c70ef4a0-b355-403b-9235-072ec13cf922.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
content: []
description: ''
purpose: []
