name: Lony Meyer Photography
favicon: null
layout_spectrum: 0.25712
typography_spectrum: 0.00084
title: Photography by Lony Meyer
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70164307-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010100'
    - '#b0b7a8'
    - '#6a5f40'
    - '#8f9687'
    - '#392b00'
  brandStrength: 0.5
  lightness: 0.3659574
  saturation: 0.606383
  rhythmicContrast: 0.6659575
purpose: []
