typography_spectrum: 0.6061128575820476
content_rating:
  adult: false
color:
  saturation: 0.43916477425955236
  brandStrength: 0.37171214492991567
  lightness: 0.9917082730680704
  brandColors:
    - '#D8CAA8'
    - '#5C832F'
    - '#284907'
    - '#382513'
    - '#363942'
  rhythmicContrast: 0.3854682929813862
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.78251285222359
analytics:
  twitter: null
  google: UA-70164307-1
  facebook: null
author:
  name: ©Copyright 2016
  email: lony@lonymeyer.com
  url: lonymeyer.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/73da66f3-68cf-45b2-9961-b24e223ffb9b.png
name: Lony Meyer Photography
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Norway
    id: 6ef0d8d6-b65c-44d9-966d-1e70050eadea
    type: content
  - name: My Bio
    id: b7389f8e-5b1b-4015-b072-cfd39223b0b0
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c70ef4a0-b355-403b-9235-072ec13cf922.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Newest from the Last Trip
description: ''
purpose: []
