layout_spectrum: 0.6985076318597329
typography_spectrum: 0.8145843929269048
color:
  saturation: 0.6468311321244824
  brandStrength: 0.40104218085370225
  lightness: 0.8126691243338334
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  rhythmicContrast: 0.8342769516205027
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-70164307-1
  facebook: null
author:
  name: ©Copyright 2016
  email: lony@lonymeyer.com
  url: lonymeyer.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/73da66f3-68cf-45b2-9961-b24e223ffb9b.png
name: Lony Meyer Photography
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Norway
    id: 6ef0d8d6-b65c-44d9-966d-1e70050eadea
    type: content
  - name: My Bio
    id: b7389f8e-5b1b-4015-b072-cfd39223b0b0
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c70ef4a0-b355-403b-9235-072ec13cf922.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: A splash of old paint
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b9997bf2-4568-477e-967b-7a4972da709a.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b9997bf2-4568-477e-967b-7a4972da709a.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Old paint from Bradbury & Bradbury
purpose: []
