layout_spectrum: 0.4569343740544697
typography_spectrum: 0.6593957750440235
color:
  saturation: 0.24570511092007677
  brandStrength: 0.9028731837559787
  lightness: 0.06708408459172685
  brandColors:
    - '#B4AF91'
    - '#787746'
    - '#40411E'
    - '#32331D'
    - '#C03000'
  rhythmicContrast: 0.9880575901590803
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-70164307-1
  facebook: null
author:
  name: ©Copyright 2015-2017
  email: lony@lonymeyer.com
  url: lonymeyer.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/73da66f3-68cf-45b2-9961-b24e223ffb9b.png
name: Lony Meyer Photography
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Norway
    id: 6ef0d8d6-b65c-44d9-966d-1e70050eadea
    type: content
  - name: My Bio
    id: b7389f8e-5b1b-4015-b072-cfd39223b0b0
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/30b0197b-ef5a-4fa0-8cc8-77e024f93fb1.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: more coming soon...
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FzfBo_epJDNI%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DzfBo_epJDNI&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FzfBo_epJDNI%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Marc Gammon
          url: 'https://www.youtube.com/channel/UCeKFynvxieLCJ3f0izEWi5A'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - ''
      description: online in march 2016.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=zfBo_epJDNI&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=zfBo_epJDNI&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=zfBo_epJDNI&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=zfBo_epJDNI&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=zfBo_epJDNI&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=zfBo_epJDNI'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=zfBo_epJDNI
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=zfBo_epJDNI
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/zfBo_epJDNI'
      title: website under construction...
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: contact
    url: 'mailto:lony@lonymeyer.com'
    label: Contact me
  - type: external
    url: 'https://lonymeyerphotography.smugmug.com/'
    label: View my Portfolio
