title: 'Art & Photography'
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.50168
favicon: null
name: Lony Meyer Photography
purpose: []
analytics:
  twitter: null
  google: UA-70164307-1
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.3659574
  saturation: 0.606383
  rhythmicContrast: 0.6659575
  brandColors: []
typography_spectrum: 0.1361702
